name: moxunittest

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: joergbrech/moxunit-action@master
       with:
        tests: tests my_extra_testfile.m
        with_coverage: true
        cover_xml_file: coverage.xml
     - uses: codecov/codecov-action@v1
       with:
        file: ./coverage.xml
