name: moxunittest

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: joergbrech/moxunit-action@v1
       with:
         tests: testing/run_test.m
